name: splittr
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: '3.24.3'

dependencies:
  bloc: ^8.1.4

  cloud_firestore: ^5.2.1

  cupertino_icons: ^1.0.6

  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6

  fpdart: 1.1.0

  freezed_annotation: ^2.4.4

  get_it: ^8.0.0

  injectable: ^2.4.4

  intl: 0.19.0

  json_annotation: ^4.9.0

  lottie: ^3.1.2
  pin_code_fields: 8.0.1

  recase: 4.1.0

  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.12

  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter

  freezed: ^2.5.7

  injectable_generator: ^2.6.2

  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/animations/
