// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSzCy6mzcCUQSM1j3R6ckQwso3eu3ZfSc',
    appId: '1:68709953361:web:0698ac49906138aec9ad70',
    messagingSenderId: '68709953361',
    projectId: 'splittr-ccdeb',
    authDomain: 'splittr-ccdeb.firebaseapp.com',
    storageBucket: 'splittr-ccdeb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJUvmhit1s6rJdK9vVBJxHZ_kk8asTvz4',
    appId: '1:68709953361:android:47da2e1bc3705e15c9ad70',
    messagingSenderId: '68709953361',
    projectId: 'splittr-ccdeb',
    storageBucket: 'splittr-ccdeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMMYPH9h0srXCJ-HZySt1eYFVHT158Syo',
    appId: '1:68709953361:ios:00806367835cb19fc9ad70',
    messagingSenderId: '68709953361',
    projectId: 'splittr-ccdeb',
    storageBucket: 'splittr-ccdeb.appspot.com',
    iosClientId: '68709953361-8c0440uu3p82vob133arl87c3121s0hf.apps.googleusercontent.com',
    iosBundleId: 'com.example.splitter',
  );
}
